import streamlit as st
import os
import traceback
from state import AgentState
from config import OUTPUT_DIR, validate_config
from tools.report_generator import save_markdown_report
from tools.email_sender import create_zip, send_email

st.set_page_config(page_title="Academic Learning Path", page_icon="🎓", layout="wide")
st.title("🎓 Academic Learning Path Generator")
st.caption("AI-powered beginner learning path | Search -> Download -> Analyze -> Rank -> Write -> Email")

PROGRESS = {
    "planner": ("📋", "Planning search strategy...", 5),
    "search": ("🔍", "Searching papers on arXiv & Semantic Scholar...", 15),
    "downloader": ("⬇️", "Downloading PDFs from arXiv...", 30),
    "reader": ("📖", "Analyzing paper difficulty and content...", 45),
    "ranker": ("📊", "Ranking papers from easiest to hardest...", 65),
    "writer": ("✍️", "Writing personalized learning path...", 80),
    "email": ("📧", "Packaging and sending email...", 95),
}

tab1, tab2 = st.tabs(["🚀 Generate Path", "📂 Saved Reports"])

with tab1:
    col1, col2 = st.columns([1, 2])
    with col1:
        st.subheader("📋 Input")
        keyword = st.text_input("Research Keyword", placeholder="e.g., Transformer, GNN, RLHF, Diffusion Model")
        st.caption("We will search for beginner-friendly papers on this topic.")
        email = st.text_input("Email (optional)", placeholder="your@email.com")
        st.caption("Receive the papers and learning path by email.")
        api_key = os.getenv("DEEPSEEK_API_KEY") or os.getenv("OPENAI_API_KEY") or ""
        if not api_key:
            st.warning("API Key not set. Set DEEPSEEK_API_KEY.", icon="⚠️")
        run_btn = st.button("🚀 Generate Learning Path", type="primary", use_container_width=True)

    with col2:
        st.subheader("📊 Progress")
        progress_placeholder = st.empty()

    if run_btn:
        if not keyword:
            st.error("Please enter a research keyword.")
        else:
            issues = validate_config()
            if issues:
                for issue in issues:
                    st.warning(issue)

            with progress_placeholder.container():
                st.info("Running multi-agent pipeline...")
                bar = st.progress(0, text="Starting...")
                log = st.empty()

                def step(name, msg, pct):
                    bar.progress(pct, text=PROGRESS[name][1])
                    log.info(msg)

                try:
                    from agents.planner import planner_agent
                    from agents.search import search_agent
                    from agents.downloader import downloader_agent
                    from agents.reader import reader_agent
                    from agents.ranker import ranker_agent
                    from agents.writer import writer_agent

                    state = {"research_keyword": keyword, "email_recipient": email or "1739362977@qq.com"}

                    # 1. Planner
                    state = planner_agent(state)
                    step("planner", state.get("status_message",""), 5)

                    # 2. Search
                    state = search_agent(state)
                    step("search", state.get("status_message",""), 15)

                    # 3. Downloader
                    state = downloader_agent(state)
                    step("downloader", state.get("status_message",""), 30)

                    # 4. Reader
                    state = reader_agent(state)
                    step("reader", state.get("status_message",""), 45)

                    # 5. Ranker
                    state = ranker_agent(state)
                    step("ranker", state.get("status_message",""), 65)

                    # 6. Writer
                    state = writer_agent(state)
                    step("writer", state.get("status_message",""), 80)

                    report = state.get("learning_path_report", "")
                    if report:
                        report_path = save_markdown_report(report, "learning_path")
                        bar.progress(95, text="Packaging and sending email...")
                        ranked = state.get("ranked_papers", [])
                        downloaded = state.get("downloaded_papers", [])
                        zip_path = create_zip(downloaded, report_path)
                        state["zip_path"] = zip_path

                        recipient = email.strip() if email and email.strip() else "1739362977@qq.com"
                        subject = f"[Learning Path] {keyword} - Beginner Paper Reading List"
                        html_body = f"""<h2>Your Learning Path: {keyword}</h2><p>Hi! Here is your personalized beginner learning path for <b>{keyword}</b>.</p><p>Contains <b>{len(ranked)} curated papers</b> ranked from easiest to hardest, plus full PDF downloads.</p><p>Happy reading!</p><hr><small>Generated by AI Multi-Agent Learning Path System</small>"""
                        sent = send_email(subject, html_body, zip_path, recipient)
                        if sent:
                            log.success(f"Email sent to {recipient}")
                        else:
                            log.warning(f"Email not sent (check EMAIL_PASSWORD). Report saved locally.")

                        bar.progress(100, text="Complete!")
                        st.success(f"Learning path with {len(ranked)} papers generated!")

                        with st.expander("Learning Path Report", expanded=True):
                            st.markdown(report)
                        st.download_button("Download Report", report, file_name="learning_path.md", mime="text/markdown")
                        st.caption(f"Papers saved in: {os.path.abspath('papers')}")
                        st.caption(f"Zip: {zip_path}")
                    else:
                        st.warning("No report generated.")
                except Exception as e:
                    st.error(f"Error: {e}")
                    st.code(traceback.format_exc())

with tab2:
    st.subheader("Saved Reports")
    if os.path.exists(OUTPUT_DIR):
        files = sorted(os.listdir(OUTPUT_DIR), reverse=True)
        if files:
            for fn in files[:30]:
                fp = os.path.join(OUTPUT_DIR, fn)
                st.text(fn)
                if fn.endswith(".md"):
                    with open(fp, "r", encoding="utf-8") as ff:
                        content = ff.read()
                    with st.expander(f"Preview: {fn}"):
                        st.markdown(content[:5000])
        else:
            st.caption("No saved reports yet. Generate a learning path!")
    else:
        st.caption("Output directory not found.")
