"""Agent state definitions for the Academic Learning Path System."""

from typing import TypedDict, List, Dict, Optional, Literal


class PaperMeta(TypedDict, total=False):
    """Metadata for a downloaded paper."""
    title: str
    authors: str
    year: str
    venue: str
    abstract: str
    url: str
    arxiv_id: str
    citation_count: int
    local_path: str
    page_count: int


class RankedPaper(TypedDict, total=False):
    """A paper with difficulty ranking and learning recommendation."""
    title: str
    authors: str
    year: str
    arxiv_id: str
    local_path: str
    difficulty_score: float
    difficulty_label: str
    reason: str
    learning_goal: str
    prerequisite: str
    estimated_hours: float
    key_sections: str
    algorithm_improvement: str
    benchmark_data: str


class AgentState(TypedDict, total=False):
    # Input
    research_keyword: str
    email_recipient: str

    # Planner output
    search_queries: List[str]

    # Search output
    search_results: List[Dict]

    # Downloader output
    downloaded_papers: List[PaperMeta]

    # Reader output
    paper_analyses: List[Dict]

    # Ranker output
    ranked_papers: List[RankedPaper]

    # Writer output
    learning_path_report: str
    zip_path: str

    # ── Retrieval Agent (Phase 1) ──
    research_interest: str          # NL description (replaces single keyword)
    search_plan: "SearchPlan"       # structured plan from planner

    # Flow control
    error: Optional[str]
    status_message: str


# ═══════════════════════════════════════════════════════════════
#  Retrieval Agent types (Phase 1)
# ═══════════════════════════════════════════════════════════════

SearchStrategyType = Literal[
    "survey",         # broad survey / review papers
    "foundational",   # classic / seminal works
    "latest",         # most recent advances
    "code_centric",   # papers with code / implementations
    "alternative",    # alternative viewpoints / competing methods
]

SEARCH_SOURCE_NAMES = Literal[
    "semantic_scholar",
    "arxiv",
    "google_scholar",
    "papers_with_code",
]


class SearchStrategy(TypedDict, total=False):
    """A single search strategy within a plan."""
    type: SearchStrategyType
    query: str                       # the actual search query string
    sources: List[SEARCH_SOURCE_NAMES]  # which databases to query
    count: int                       # how many results to fetch
    year_from: Optional[int]
    year_to: Optional[int]
    reason: str                      # why this strategy (for explainability)


class SearchPlan(TypedDict, total=False):
    """Structured search plan generated by the planner."""
    core_topic: str                  # extracted core research topic
    sub_topics: List[str]            # decomposed sub-directions
    strategies: List[SearchStrategy] # ordered list of search strategies
    total_expected: int              # total papers expected
    reasoning: str                   # planner's rationale


class PaperResult(TypedDict, total=False):
    """Unified paper result from any search source."""
    title: str
    authors: str
    year: str
    venue: str
    abstract: str
    url: str
    citation_count: int
    arxiv_id: str
    paper_id: str
    source: SEARCH_SOURCE_NAMES      # which database this came from
    code_url: str                    # GitHub / code link (from PWC)
    github_stars: int                # GitHub stars (from PWC)
    doi: str                         # DOI for deduplication
