"""Report generation tools."""
import os
from datetime import datetime
from config import OUTPUT_DIR


def save_markdown_report(content: str, filename_prefix: str = "report") -> str:
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    filename = f"{filename_prefix}_{timestamp}.md"
    filepath = os.path.join(OUTPUT_DIR, filename)
    with open(filepath, "w", encoding="utf-8") as f:
        f.write(content)
    return filepath


def build_report_markdown(
    research_direction: str,
    primary_paper: dict,
    search_results: list,
    draft_report: str,
    draft_references: str,
    review_feedback: dict = None,
) -> str:
    paper_title = primary_paper.get("title", "Unknown Paper")
    lines = []
    lines.append(f"# Paper Analysis: {paper_title}")
    lines.append(f"")
    lines.append(f"> **Research Context:** {research_direction}")
    lines.append(f"> **Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    lines.append("")
    lines.append("---")
    lines.append("")

    if primary_paper:
        lines.append("## Paper Metadata")
        lines.append(f"- **Title:** {primary_paper.get('title', 'N/A')}")
        lines.append(f"- **Authors:** {primary_paper.get('authors', 'N/A')}")
        lines.append(f"- **Year:** {primary_paper.get('year', 'N/A')}")
        lines.append(f"- **Venue:** {primary_paper.get('venue', 'N/A')}")
        lines.append(f"- **Keywords:** {', '.join(primary_paper.get('keywords', []))}")
        lines.append(f"")
        lines.append(f"### Abstract")
        lines.append(f"{primary_paper.get('abstract', 'N/A')}")
        lines.append("")

    lines.append("## Analysis Review")
    lines.append(draft_report)
    lines.append("")

    lines.append("---")
    lines.append("## References")
    lines.append(draft_references)
    lines.append("")

    if review_feedback:
        lines.append("---")
        lines.append("## Review Feedback")
        lines.append(f"- **Overall Score:** {review_feedback.get('score', 'N/A')}/10")
        for k in ["completeness", "accuracy", "structure", "suggestions"]:
            if review_feedback.get(k):
                lines.append(f"- **{k.capitalize()}:** {review_feedback[k]}")
        lines.append("")

    lines.append("")
    lines.append("---")
    lines.append("*Generated by AI Multi-Agent Paper Analysis System*")
    return "\n".join(lines)
